name: Deploy MkDocs

on:
  push:
    branches:
      - main  # build docs on every push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install .
          pip install mkdocs-material mkdocstrings[python]

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
